### ISSUE TITLE
Support determining the style of hyperlinks

### ISSUE THREAD

**Issue by tfcporciuncula** [cbeyls/HtmlConverterCompose#1]
[Right now hyperlinks are always underlined](https://github.com/cbeyls/HtmlConverterCompose/blob/c25869c5ccc87f1036ff116af30e100675b336ea/htmlconverter/src/commonMain/kotlin/be/digitalia/compose/htmlconverter/internal/AnnotatedStringHtmlHandler.kt#L136) and it would be nice if it was possible for clients to define the `SpanStyle` used there.

I understand this goes beyond the scope of replacing Android's [`Html.fromHtml()`](https://developer.android.com/reference/android/text/Html#fromHtml(java.lang.String,%20int)) API, so I totally understand if it’s also out of the scope of this library. But since this may potentially be a blocker for some people (it would be for me), I thought I would still file this just in case.

I guess the simplest option would be to receive a `urlSpanStyle` as an argument for `AnnotatedStringHtmlHandler`. I’m hoping since we’re already receiving the `compactMode` boolean there, this won’t hurt the API too much.

I’ll open a PR so it hopefully helps discussing about this change. And thanks a lot for open sourcing this ❤️

**Comment by cbeyls** [comment]
Hello, thank you for your contribution, I didn't expect to receive a pull request so quickly!

I was actually considering the same change, as I prefer my hyperlinks colored and not underlined. However, API-wise, I would prefer to expose a more generic data class as third argument, that will contain more styling customizations, not just the url span style.

I'll publish a new release later today or tomorrow that includes this ability. Thank you!

**Comment by tfcporciuncula** [comment]
That's great to hear, thanks! Feel free to close my PR in this case, then ✌️

**Comment by cbeyls** [comment]
Fixed in version 0.9.0
