### ISSUE TITLE
Support <br> (instead of only <br/>)

### ISSUE THREAD

**Issue by tfcporciuncula** [cbeyls/HtmlConverterCompose#3]
I’m not a line break tag expert and I don’t have any authority over the topic, but [it seems that just `<br>` is a pretty popular and well accepted form of using the line break tag](https://stackoverflow.com/a/1946446/2352699). I actually thought this was a bug in the library since my line breaks weren’t working, but then I realized [it explicitly doesn’t do anything on the line break tag open](https://github.com/cbeyls/HtmlConverterCompose/blob/37da3df8b0ce6790476a2856aea68835230986c2/htmlconverter/src/commonMain/kotlin/be/digitalia/compose/htmlconverter/internal/AnnotatedStringHtmlHandler.kt#L50). I thought the fix would be to simply do the same thing we do on tag close, but it seems there’s more to it.

This is what the sample looks like right now, with a red box at the bottom so we can observe the bottom space of the text:

![sample](https://github.com/cbeyls/HtmlConverterCompose/assets/750114/26567c0d-b2ae-4558-a712-3f0adcad6868)

If I simply change the `<br />` to a `<br>` [in the sample](https://github.com/cbeyls/HtmlConverterCompose/blob/37da3df8b0ce6790476a2856aea68835230986c2/sample/src/commonMain/kotlin/SampleHtml.kt#L37), this is what we get:

![sample2](https://github.com/cbeyls/HtmlConverterCompose/assets/750114/bdf4c582-3a11-4a49-9373-2741fec1e26a)

We lost the line break as expected, but for some reason now we have a line break at the end of the text. So if I proceed with the fix I had in mind, this is what I get:

![sample3](https://github.com/cbeyls/HtmlConverterCompose/assets/750114/7ac08397-da91-4980-b37d-68e92db776a9)

Line break is back but 1. it’s just a single line break now for some reason, and 2. the mysterious line break in the end remains. I haven’t investigated it further and I thought I’d file the issue just in case this is already something known.

**Comment by cbeyls** [comment]
Thank you for the report, this will be fixed in the next release.
This is because currently, the line break is only handled when encountering the closing tag instead of when encountering the opening tag.

**Comment by cbeyls** [comment]
For the record, I developed the first version of the library using a different HTML parser which had a special treatment for the br tag so I didn't notice the issue during my initial tests.
In addition to the quick fix in the handler, I'll add a special case in the parser to handle the `<br>` and `</br>` tags differently, similarly to how Firefox handles them.
