### ISSUE TITLE
ClickableText is deprecated

### ISSUE THREAD

**Issue by iAbanoubSamir** [cbeyls/HtmlConverterCompose#4]
Since ClickableText that handles hyperlinks clicks is deprecated, is there a better solution?

**Comment by cbeyls** [comment]
I'm waiting for Compose 1.7.0 stable release to publish a new version of this library that will use `LinkAnnotation`.
The latest Compose stable release available today only supports `ClickableText` so it should only be considered deprecated starting Compose 1.7.0
